"""Your descriptive migration message

Revision ID: 4832e0cc9044
Revises: 
Create Date: 2024-11-16 10:46:31.693887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4832e0cc9044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.Enum('Fall', 'Spring', 'Summer', name='semester_enum'), nullable=True),
    sa.Column('is_currently_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.Column('Role', sa.Enum('Student', 'Instructor', 'Admin', name='role_enum'), nullable=False),
    sa.Column('DateCreated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('course_instructors',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('course_id', 'instructor_id')
    )
    op.create_table('course_materials',
    sa.Column('material_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('PDF', 'Video', 'Document', 'Image', name='material_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('enrollments',
    sa.Column('EnrollmentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('CourseID', sa.Integer(), nullable=False),
    sa.Column('EnrollmentDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('Status', sa.Enum('Active', 'Dropped', name='enrollment_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('EnrollmentID')
    )
    op.create_table('notifications',
    sa.Column('NotificationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Message', sa.Text(), nullable=True),
    sa.Column('DateSent', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    op.create_table('profiles',
    sa.Column('ProfileID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('ProfileID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('notifications')
    op.drop_table('enrollments')
    op.drop_table('course_materials')
    op.drop_table('course_instructors')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
